version: '3'
services:
  app:
    build: .
    container_name: agenda
    restart: always
    ports:
      - 8080:80
  mariadb:
    image: mariadb:10.9
    container_name: mariadb
    restart: always
    volumes:
      - ./db/agenda.sql:/docker-entrypoint-initdb.d/agenda.sql
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=agenda
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=1234
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
